USE pokedex;
DESC pokemon;
SELECT * FROM pokemon;
SELECT numero, nome, cor, altura_m, peso_kg from pokemon;
SELECT numero, nome FROM pokemon where geracao = 1;
SELECT nome FROM pokemon where geracao = 1 AND cor = 'amarelo';
SELECT * FROM pokemon order by total DESC limit 1;
SELECT Numero, nome, tipo1 FROM pokemon where tipo1 = 'fire';
#NAO TEM QUESTAO 9
SELECT numero, nome, defesa FROM pokemon order by numero desc, nome desc, defesa desc;
SELECT numero, nome FROM pokemon order by taxa_captura limit 1;
SELECT * FROM pokemon WHERE tipo2 <> 'null';
SELECT numero, nome, tipo1, tipo2 FROM pokemon where peso_kg > 100 AND peso_kg < 500;
SELECT numero, nome, velocidade FROM pokemon order by velocidade DESC limit 10 ;
SELECT numero, nome, tipo1, tipo2 FROM pokemon WHERE tipo2 <> 'null' AND tipo1 <> 'null' AND taxa_captura > 100 order by taxa_captura DESC;
SELECT DISTINCT tipo1 FROM pokemon; 
SELECT numero, nome, cor FROM pokemon WHERE nome like 'D%'; 
SELECT * FROM pokemon order by total DESC limit 1;
SELECT numero, nome, defesa, ataque FROM pokemon WHERE defesa > '60' AND defesa <= '70' order by total DESC;
SELECT * FROM pokemon WHERE tipo1 = 'Planta' AND tipo2 = 'Venenoso' AND cor <> 'Green' order by nome;
SELECT * FROM pokemon WHERE nome like '___y%'; 
SELECT ataque_especial FROM pokemon order by ataque_especial DESC LIMIT 1;
SELECT numero, nome, altura_m FROM pokemon WHERE altura_m > 2.10;
SELECT DISTINCT cor FROM pokemon ORDER BY cor;
SELECT nome, velocidade FROM pokemon WHERE velocidade BETWEEN  30  AND 70 ORDER BY nome, velocidade DESC;
SELECT * FROM pokemon WHERE lendario = 1 ORDER BY total DESC;
SELECT * FROM pokemon WHERE geracao = 1 AND taxa_captura = 255;
SELECT * FROM pokemon WHERE nome = 'Pikachu' OR nome = 'Squirtle' OR nome = 'BUlbasaur' OR nome = 'Charmander' ORDER BY total DESC;
SELECT * FROM pokemon WHERE geracao = 1 AND nome LIKE 'D%' AND tipo2 IS NULL ORDER BY taxa_captura, total DESC;
SELECT numero, nome, total, taxa_captura FROM pokemon WHERE lendario = 1 ORDER BY total DESC, taxa_captura DESC LIMIT 5;
SELECT numero, nome, peso_kg from pokemon where peso_kg BETWEEN 2 AND 3;
SELECT numero, nome, tipo1, tipo2 FROM pokemon where tipo1 = 'Normal' AND tipo2 IS NULL AND lendario <> '1';
SELECT numero, nome, tipo1, tipo2, cor FROM pokemon WHERE tipo1 = 'Water' ORDER BY nome;
SELECT * FROM pokemon ORDER BY velocidade limit 10;
SELECT * FROM pokemon WHERE nome LIKE '%a';
SELECT numero, nome, tipo1, tipo2, cor FROM pokemon WHERE tipo1 = 'Fire' AND cor <> 'Red' order by nome;
SELECT DISTINCT peso_kg FROM pokemon ORDER BY peso_kg;
SELECT numero, nome, hp FROM pokemon WHERE hp BETWEEN 0 AND 100 ORDER BY hp , nome;
SELECT numero, nome, hp, ataque, defesa, total FROM pokemon WHERE hp >= 100 AND ataque >= 100 AND defesa >= 100;
SELECT * FROM pokemon WHERE tipo1 = 'Water' AND tipo2 = 'Gelo' ORDER BY total DESC;
